server:
  port: 8088
  servlet:
    context-path: /auth



spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5
    max-active: 10
    max-idle: 5
    max-wait: 10000
    min-idle: 2
    password: panwei960801
    url: jdbc:mysql://localhost:3306/auth_shiro?useSSL=false&serverTimezone=UTC
    username: root
  #kafka消息队列配置
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: sys_grant_log_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  config:
    location: classpath*:application.yml


#mybatis-plus框架相关配值
mybatis-plus:
  type-aliases-package: com.iflytek.auth.common.pojo
  mapper-locations: classpath*:mappers/*.xml


#登录主页url
auth:
  manager:
    filter:
      login:
        excludeUrls: /login/token
    login:
      url: http://172.31.186.189/login

#定时任务相关配置
task:
    queueSize: 1024
    poolSize: 10

#jwt相关配置
jwt:
  access-token:
    expire-time: 600000
    id: 72843755D44072F7E0F70A2973B95018
  refresh-token:
    expire-time: 86400000
    id: 6DF8E75F5F6AFF997C75A20B61EDD76A
